### ISSUE TITLE
Tray Icon Right-Click Behavior

### ISSUE THREAD

**Issue by alexfornuto** [f-koehler/KTailctl#137] opened 2024-02-12 16:16 UTC
When right-clicking on the system tray icon, the context menu opens as expected, but the main window also toggles on-off at the same time. I suspect this is a bug, and that the primary click should toggle window visibility while alternate click **only** brings up the context menu.

This behavior occurred with a "system tray" from both i3-bar and polybar.

**Comment by f-koehler** [comment] 2024-02-17 14:52
> When right-clicking on the system tray icon, the context menu opens as expected, but the main window also toggles on-off at the same time. I suspect this is a bug, and that the primary click should toggle window visibility while alternate click **only** brings up the context menu.
> 
> This behavior occurred with a "system tray" from both i3-bar and polybar.

mhmh, interesting. I cannot reproduce this on Plasma. Will have to check it out on i3.

**Comment by f-koehler** [comment] 2024-02-17 16:09
Reproduced in a Pop OS VM using i3-bar. This should be fixable by filtering the activation reason when deciding whether to toggle window visibility. Implemented in #140, needs testing in VM.

**Comment by f-koehler** [comment] 2024-02-17 16:17
Fix confirmed, will be released in v0.15.0.

**Closed by f-koehler** 2024-02-17 16:17 UTC
Labels: bug

**Comment by alexfornuto** [comment] 2024-02-20 16:13
Confirmed, thanks!
