### ISSUE TITLE
Empty button Labels

### ISSUE THREAD

**Issue by alexfornuto** [f-koehler/KTailctl#121] opened 2024-01-22 17:51 UTC
Thanks for making this project! I just installed it from flathub, and find that none of the buttons or sliders have labels:

![image](https://github.com/f-koehler/KTailctl/assets/2349184/3ac387c7-7b41-4d28-9a62-2a36edc257d9)

This is on Pop!_OS 22.04 LTS. Happy to provide any other information that might help to debug.

EDIT: Additional info: Running on i3, so if this is looking for colors from a DE that isn't there, that might be why?

**Comment by f-koehler** [comment] 2024-01-23 08:50
This looks like it does not find/use the icons from the breeze theme (as well as the QT theme in general). I thought that stuff came bundled in the frameworks, so I will have to do some investigation.

@alexfornuto  In case I want to reproduce this, you just install i3 via apt, right?

**Comment by f-koehler** [comment] 2024-01-23 08:55
Can you maybe share the list of installed flatpaks? `flatpak list`/`flatpak list --user` (depending on how you installed it)?

**Comment by alexfornuto** [comment] 2024-01-23 16:20
> In case I want to reproduce this, you just install i3 via apt, right?

@f-koehler Yes, the package is `i3-wm`.

> Can you maybe share the list of installed flatpaks? flatpak list/flatpak list --user (depending on how you installed it)?

After trying (and failing) to build it from source, I installed with the pak from flathub:

```
❯ flatpak list --user 
Name                                                         Application ID                                                  Version               Branch
Trayscale                                                    dev.deedles.Trayscale                                           v0.10.4               stable
KTailctl                                                     org.fkoehler.KTailctl                                           0.13.0                stable
flatpak_external_data_checker translations                   org.flathub.flatpak_external_data_checker.Locale                                      stable
Mesa                                                         org.freedesktop.Platform.GL.default                             23.3.2                23.08
Mesa (Extra)                                                 org.freedesktop.Platform.GL.default                             23.3.2                23.08-extra
openh264                                                     org.freedesktop.Platform.openh264                               2.1.0                 2.2.0
freedesktop development platform translations                org.freedesktop.Sdk.Locale                                                            23.08
GNOME Application Platform version 45                        org.gnome.Platform                                                                    45
Adwaita theme                                                org.kde.KStyle.Adwaita                                                                5.15-23.08
KDE Application Platform                                     org.kde.Platform                                                                      5.15-23.08
```

**Comment by f-koehler** [comment] 2024-01-24 02:47
@alexfornuto Thanks for the info. I will investigate.

**Comment by f-koehler** [comment] 2024-02-02 07:31
Fixed in #130

**Comment by f-koehler** [comment] 2024-02-02 07:35
@alexfornuto , I will release an updated version v0.14.1 that resolves this issue. Should appear on flathub in a few hours.

**Closed** 2024-02-02 07:34 UTC
Labels: bug

**Comment by alexfornuto** [comment] 2024-02-05 16:55
Confirmed as fixed, thanks!
