### ISSUE TITLE
Tray icon could provide more feedback

### ISSUE THREAD

**Issue by mankoff** [f-koehler/KTailctl#323] opened 2024-12-08 15:34 UTC
Currently tray icon is always 3x3 dots. Green if Tailscale is running, red if not.

It could provide more feedback, for example, color or shape if exit node is active local or remote, shields up mode, etc.

**Comment by f-koehler** [comment] 2024-12-08 16:16
@mankoff, thank you. I was already planning on doing that, but I just did not have time to design new icons. When I tried in the past, they looked very blurry and I postponed this.

I am closing this issue as it is a duplicate of #144, but I will incorporate your ideas regarding shields up mode.

**Closed by f-koehler** 2024-12-08 16:16 UTC
Labels: duplicate
