### ISSUE TITLE
Cant start on Arcolinux

### ISSUE THREAD

**Issue by oldman20** [f-koehler/KTailctl#187] opened 2024-04-04 04:25 UTC
Im running 24.4.03 Arcolinux
Failed to load module "xapp-gtk3-module"
```
$ flatpak run org.fkoehler.KTailctl
Gtk-Message: 11:22:39.568: Failed to load module "xapp-gtk3-module"
Gtk-Message: 11:22:39.568: Failed to load module "xapp-gtk3-module"
[2024-04-04T11:22:39][warning] Qt: Session management error: Could not open network socket
[2024-04-04T11:22:39][warning] QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: HighContrastInverse, HighContrast, Adwaita-HighContrastInverse, Adwaita-HighContrast, Adwaita-Dark, Adwaita, Breeze, Windows, Fusion
[2024-04-04T11:22:39][warning] Cyclic dependency detected between "qrc:/qt/qml/org/kde/desktop/private/TextFieldContextMenu.qml" and "qrc:/qt/qml/org/kde/desktop/MenuItem.qml"
*** stack smashing detected ***: terminated

```

Im  installed via flatpak

**Comment by f-koehler** [comment] 2024-04-04 08:21
The latest version of `Arcolinux` I could find on their website was `24.02.04`. How do you install tailscale on that distribution? I have never heard of this distribution before and they ship their own pacman repositories which do not contain tailscale.  So I was not able to reproduce your issue.

**Comment by oldman20** [comment] 2024-04-04 08:38
> The latest version of `Arcolinux` I could find on their website was `24.02.04`. How do you install tailscale on that distribution? I have never heard of this distribution before and they ship their own pacman repositories which do not contain tailscale. So I was not able to reproduce your issue.
I download from here
https://ant.seedhost.eu/arcolinux/
```
$ iso
ISO_RELEASE=v24.04.03
ISO_CODENAME=ArcoLinuxL
ISO_BUILD=Sat Mar 16 11:30:45 AM CET 2024
```

**Comment by f-koehler** [comment] 2024-04-05 03:00
I was not able to reproduce:

1. Downloaded and installed ArcoLinuxL 24.02.04 in a VM.
2. Update the system.
3. Installed flatpak.
4. Added flathub as a user repository.
5. Installed `org.fkoehler.KTailctl` in user mode.
6. Started the program, it does not crash.

Just to make sure, I also signed into my tailnet and the app shows all information correctly.

Can you show me the output of `flatpak info -vv org.fkoehler.KTailctl`?

**Comment by oldman20** [comment] 2024-04-05 08:05
> I was not able to reproduce:
> 
>     1. Downloaded and installed ArcoLinuxL 24.02.04 in a VM.
> 
>     2. Update the system.
> 
>     3. Installed flatpak.
> 
>     4. Added flathub as a user repository.
> 
>     5. Installed `org.fkoehler.KTailctl` in user mode.
> 
>     6. Started the program, it does not crash.
> 
> 
> Just to make sure, I also signed into my tailnet and the app shows all information correctly.
> 
> Can you show me the output of `flatpak info -vv org.fkoehler.KTailctl`?

Here Dev!
```
$ flatpak info -vv org.fkoehler.KTailctl
F: No installations directory in /etc/flatpak/installations.d. Skipping

KTailctl - GUI for Tailscale mesh network

          ID: org.fkoehler.KTailctl
         Ref: app/org.fkoehler.KTailctl/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.16.0
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 17,9 MB
     Runtime: org.kde.Platform/x86_64/6.6
         Sdk: org.kde.Sdk/x86_64/6.6

      Commit: f3e892bea32e8c80d462a5422437a1e579445d851f909e1c072a5d79e4454e48
      Parent: 2731e948c73b69e480fc9f0ba024c22b63019b81f479b2afd71019711d18e517
     Subject: Fix commit hash for KTailctl. (e8fb2811)
        Date: 2024-04-01 17:10:48 +0000

```

**Comment by f-koehler** [comment] 2024-04-05 08:16
Currently, I have no idea what the issue might be since it does not happen for me. I found one potential issue related to the NVIDIA GPU driver: https://github.com/flathub/com.calibre_ebook.calibre/issues/195

Di you happen to have an NVIDIA GPU?

**Comment by f-koehler** [comment] 2024-04-12 04:14
Can you share the output of `flatpak list` so we can see which runtime is used? You are likely suffering from this bug: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1676 / https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/211

If that is the case, this unfortunately has to be resolved upstream. I do not have any hardware to test it out.

**Comment by oldman20** [comment] 2024-04-26 04:25
> Can you share the output of `flatpak list` so we can see which runtime is used? You are likely suffering from this bug: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1676 / [flathub/org.freedesktop.Platform.GL.nvidia#211](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/211)
> 
> If that is the case, this unfortunately has to be resolved upstream. I do not have any hardware to test it out.
Here info mr @f-koehler:
$ flatpak list
Name                    Application ID                            Version Branch      Installation
KTailctl                org.fkoehler.KTailctl                     0.16.0  stable      system
Mesa                    org.freedesktop.Platform.GL.default       24.0.5  23.08       system
Mesa (Extra)            org.freedesktop.Platform.GL.default       24.0.5  23.08-extra system
nvidia-390-157          …g.freedesktop.Platform.GL.nvidia-390-157         1.4         system
openh264                org.freedesktop.Platform.openh264         2.1.0   2.2.0       system
KDE Application Platfo… org.kde.Platform                                  6.6         system

**Comment by oldman20** [comment] 2024-04-26 04:26
> I was not able to reproduce:
> 
>     1. Downloaded and installed ArcoLinuxL 24.02.04 in a VM.
> 
>     2. Update the system.
> 
>     3. Installed flatpak.
> 
>     4. Added flathub as a user repository.
> 
>     5. Installed `org.fkoehler.KTailctl` in user mode.
> 
>     6. Started the program, it does not crash.
> 
> 
> Just to make sure, I also signed into my tailnet and the app shows all information correctly.
> 
> Can you show me the output of `flatpak info -vv org.fkoehler.KTailctl`?

i tried like your way on virtualbox, it also working, but when repeart on host machine, it not work
`$ flatpak run org.fkoehler.KTailctl
Gtk-Message: 11:26:42.128: Failed to load module "xapp-gtk3-module"
Gtk-Message: 11:26:42.129: Failed to load module "xapp-gtk3-module"
[2024-04-26T11:26:42][warning] Qt: Session management error: Could not open network socket
[2024-04-26T11:26:42][warning] QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: Breeze, Windows, Fusion
[2024-04-26T11:26:42][warning] Cyclic dependency detected between "qrc:/qt/qml/org/kde/desktop/private/TextFieldContextMenu.qml" and "qrc:/qt/qml/org/kde/desktop/MenuItem.qml"
*** stack smashing detected ***: terminated
`

**Comment by oldman20** [comment] 2024-05-02 06:12
Update: today after update system, i can run kTailctl, but i cant see files sent from others device, it just say success on others device but cant see file on /home/my-user-name/Downloads/taildrop
And i can sent file from machine installed kTailctl. Dont know why? I tried set location received files and restart service, even restart machine. Nothing work!
and strange: taildrop directory not create automatic, i tried created it manual and trying sent file, client said success but cant file it on machine kTailctl?

**Comment by oldman20** [comment] 2024-05-02 06:16
here the terminal out after run kTailctl from Terminal, when i tried set location received:

```
$ flatpak run org.fkoehler.KTailctl
Gtk-Message: 13:14:20.215: Failed to load module "xapp-gtk3-module"
Gtk-Message: 13:14:20.215: Failed to load module "xapp-gtk3-module"
[2024-05-02T13:14:20][warning] Qt: Session management error: Could not open network socket
[2024-05-02T13:14:20][warning] QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: Breeze, Windows, Fusion
"/home/chuctran/Downloads/taildrop/" is not a directory
[2024-05-02T13:14:20][warning] Cyclic dependency detected between "qrc:/qt/qml/org/kde/desktop/private/TextFieldContextMenu.qml" and "qrc:/qt/qml/org/kde/desktop/MenuItem.qml"
[2024-05-02T13:14:20][warning][qrc:Peers.qml:10] qrc:Peers.qml:10:1: QML ScrollablePage: Created graphical object was not placed in the graphics scene.
Warning: client version "1.62.1-ERR-BuildInfo" != tailscaled server version "1.64.0"
[2024-05-02T13:14:21][critical][/run/build/ktailctl/src/statistics.cpp:48] No down speed statistics for peer ""
[2024-05-02T13:14:21][critical][/run/build/ktailctl/src/statistics.cpp:39] No up speed statistics for peer ""
[2024-05-02T13:14:21][critical][/run/build/ktailctl/src/statistics.cpp:48] No down speed statistics for peer ""
[2024-05-02T13:14:21][critical][/run/build/ktailctl/src/statistics.cpp:39] No up speed statistics for peer ""
[2024-05-02T13:14:21][warning][qrc:Peers.qml:91] qrc:Peers.qml:91: TypeError: Cannot read property 'average1Second' of null
[2024-05-02T13:14:21][warning][qrc:Peers.qml:99] qrc:Peers.qml:99: TypeError: Cannot read property 'average1Second' of null
[2024-05-02T13:14:21][warning][qrc:Peers.qml:91] qrc:Peers.qml:91: TypeError: Cannot read property 'average1Second' of null
[2024-05-02T13:14:21][warning][qrc:Peers.qml:99] qrc:Peers.qml:99: TypeError: Cannot read property 'average1Second' of null
[2024-05-02T13:14:42][warning][qrc:About.qml:11] qrc:About.qml:11:1: QML AboutPage: Created graphical object was not placed in the graphics scene.
[2024-05-02T13:14:44][warning][qrc:Settings.qml:13] qrc:Settings.qml:13:1: QML ScrollablePage: Created graphical object was not placed in the graphics scene.
[2024-05-02T13:14:52][warning][qrc:Settings.qml:359] qrc:Settings.qml:359: TypeError: Cannot read property '0' of undefined
```

**Comment by oldman20** [comment] 2024-05-02 06:23
after research, i found default location received files is `/var/lib/tailscale/files/` and found files which i sent above. So i think default location set in kTailctl ís not work. Maybe it is bug? anyone has same issue?

**Comment by f-koehler** [comment] 2024-05-21 09:43
The tailscale set integration seems to be indeed a bit broken. I am tracking it in a separate issue (#201) and will work on it in the future. But good to hear that you can now at least launch the app and that the rest of it seems to work. I will close this issue for now.

**Closed by f-koehler** 2024-05-21 09:43 UTC
Labels: bug, help wanted
